# Generated by Django 4.2 on 2025-09-25 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults_count', models.IntegerField()),
                ('children_count', models.IntegerField(blank=True, null=True)),
                ('infants_count', models.IntegerField(blank=True, null=True)),
                ('dep_duration', models.DateTimeField()),
                ('arr_duration', models.DateTimeField(blank=True, default=None, null=True)),
                ('duration', models.TimeField()),
                ('currencyCode', models.CharField(max_length=3)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('there_seg', models.BooleanField(default=True)),
                ('dep_iataCode', models.CharField(max_length=3)),
                ('dep_airport', models.CharField(max_length=50)),
                ('dep_terminal', models.CharField(max_length=2, null=True)),
                ('dep_dateTime', models.DateTimeField()),
                ('arr_iataCode', models.CharField(max_length=3)),
                ('arr_airport', models.CharField(max_length=50)),
                ('arr_terminal', models.CharField(max_length=2, null=True)),
                ('arr_dateTime', models.DateTimeField()),
                ('carrierCode', models.CharField(max_length=2)),
                ('number', models.CharField(max_length=4, null=True)),
                ('aircraftCode', models.CharField(max_length=4, null=True)),
                ('operating', models.CharField(max_length=2, null=True)),
                ('duration', models.TimeField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightoffer')),
            ],
        ),
        migrations.CreateModel(
            name='FlightRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('currencyCode', models.CharField(max_length=50)),
                ('originLocationCode', models.CharField(max_length=50)),
                ('destinationLocationCode', models.CharField(max_length=50)),
                ('departureDate', models.DateField()),
                ('returnDate', models.DateField(blank=True, null=True)),
                ('adults', models.IntegerField(default=1)),
                ('children', models.IntegerField(blank=True, null=True)),
                ('infants', models.IntegerField(blank=True, null=True)),
                ('cabin', models.CharField(blank=True, max_length=20, null=True)),
                ('includedAirlines', models.CharField(blank=True, max_length=200, null=True)),
                ('excludedAirlines', models.CharField(blank=True, max_length=200, null=True)),
                ('travelClass', models.CharField(blank=True, max_length=50, null=True)),
                ('nonStop', models.BooleanField(blank=True, null=True)),
                ('maxPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flightoffer',
            name='flightRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightrequest'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('order_id', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает подтверждения'), ('CONFIRMED', 'Подтверждено'), ('CANCELLED', 'Отменено')], default='PENDING', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_code', models.CharField(max_length=3)),
                ('passenger_data', models.JSONField(default=dict)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightoffer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
