# Generated by Django 4.2 on 2025-10-11 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flightrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flightoffer',
            name='flightRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightrequest'),
        ),
        migrations.AddField(
            model_name='booking',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightoffer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
