# Generated by Django 4.2 on 2025-11-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirLineRaiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_code', models.CharField(max_length=10)),
                ('airline_name', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
