# Generated by Django 4.2 on 2025-11-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_airlineraiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlineraiting',
            name='airline_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
