# Generated by Django 4.2 on 2025-11-15 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_airlineraiting_airline_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightsegment',
            name='airlineRaiting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.airlineraiting'),
        ),
    ]
