# Generated by Django 4.2 on 2025-10-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
